### ISSUE TITLE
Request for basic/normal permissions 

### ISSUE THREAD

**Issue by helio-frota** [trustification/scale-testing#3]
Hi folks I can't select a reviewer:

![2024-05-20_08-45](https://github.com/trustification/scale-testing/assets/6443576/34ad41a7-789a-4fa6-854a-ff48a1300d0d)
 
thanks

**Comment by gildub** [comment]
@helio-frota, as I don't have admin privileges please approach @bobmcwhirter, @ctron or @jcrossley3 .

**Comment by ctron** [comment]
@gildub I noticed that you are admin on this repository. I anyway added the @trustification/committers team to the repository.
